on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      OCP_PULL_SECRET: ${{ secrets.OCP_PULL_SECRET }}
      TF_VERSION: 1.6.3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Check env 
        id:  list
        run: |
              pwd
              ls -lart
              env
              
      - name: Create pull Secret 
        run: 'echo "${OCP_PULL_SECRET}" > pull_secret.txt'
        shell: bash
      
      - name: Check env 
        id: cat 
        run: cat pull_secret.txt
      
