on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      export ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}
      OCP_PULL_SECRET: ${{ secrets.OCP_PULL_SECRET }}
      TF_VERSION: 1.6.3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
                     
      - name: Create OCP pull secret 
        run: python -c "import os; file = open('pull_secret.json', 'w'); file.write(os.environ['OCP_PULL_SECRET']); file.close()"
        shell: bash

      - name: Create SSH keys from Secret
        run: |
                  mkdir -p /home/runner/.ssh
                  # DOKKU_SSH_KEY is the name of the repository secret
                  echo "${{ secrets.SSH_PUBLIC_KEY }}" > /home/runner/.ssh/id_rsa.pub
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/id_rsa
                  chmod 600 /home/runner/.ssh/id_rsa.pub /home/runner/.ssh/id_rsa
       
      - name: Check env 
        id: list_files 
        run: |
              pwd
              ls -lart

      - name: 'Log into Azure using github secret AZURE_CREDENTIALS'
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: 'Run az commands'
        run: |
          az account show
          az group list              

      - name: Terraform init 
        id: init
        run: terraform init

      - name: Terraform plan
        id: plan
        run: |
             terraform plan -var "pull_secret_path=pull_secret.json" \
             -var "subscription_id=$ARM_SUBSCRIPTION_ID" \
             -var "cluster_name=test-aro" -no-color

      - name: Terraform apply
        id: apply
        run: terraform apply -var "pull_secret_path=pull_secret.json" \
             -var "subscription_id=$ARM_SUBSCRIPTION_ID" \
             -var "cluster_name=test-aro" -auto-approve              
      
